os:
  - osx
language: swift

jobs:
   include:
     - stage: test
       name: test on xcode 10.3 iOS 12.4
       osx_image: xcode10.3
       script:
           - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit_ExampleUITests -sdk iphonesimulator12.4 -destination "OS=12.4,name=iPhone Xs" | xcpretty

     - stage: test
       name: test on xcode 11.1 iOS 13.1
       osx_image: xcode11.2
       script:
           - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit_ExampleUITests -sdk iphonesimulator13.2 -destination "OS=13.2,name=iPhone 11 Pro" | xcpretty
