language: swift

os:
  - osx

matrix:
  include:
    - osx_image: xcode10.3
    - osx_image: xcode11.5

addons:
  homebrew:
    brewfile: true
    update: true

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit_ExampleUITests -sdk iphonesimulator12.4 -destination "OS=12.4,name=iPhone Xs" | xcpretty
- carthage build --archive
- pod lib lint
